package com.project.utils.enums

enum AuthorityType {
    /**
     * to define type of user
     */
    ROLE_SUPER_ADMIN("SUPER USER"),
    ROLE_MANAGEMENT_ADMIN("MANAGEMENT USER"),
    ROLE_ACCOUNT_ADMIN("ACCOUNT USER"),
    ROLE_USER("GENERAL USER"),
    ROLE_GUEST_USER("GUEST USER"),

    /**
     * to define super admin user action
     */
    ROLE_SYSTEM_PARAMETER("SYSTEM PARAMETER"),
    ROLE_USER_CREATION("CREATE NEW USER"),
    ROLE_SWITCH_USER("SWITCH USER"),

    /**
     * to define authority
     */
    ROLE_DASHBOARD("DASHBOARD"),
    ROLE_ORGANIZATION_PROFILE("ORGANIZATION PROFILE"),
    ROLE_ORGANIZATION_PARAMETER("ORGANIZATION PARAMETER"),
    ROLE_AUTH_PARAMETER("SECURITY PARAMETER"),

    ROLE_FUEL("FUEL SYSTEM"),
    ROLE_HARDWARE("HARDWARE SYSTEM"),

    ROLE_CREDIT("CREDIT AUTHORITY"),
    ROLE_RECEIPT("RECEIPT ENTRY"),
    ROLE_PAYMENT("PAYMENT ENTRY"),

    ROLE_STOCK_LEDGER("STOCK LEDGER"),
    ROLE_DEBTORS_CREDITORS("DEBTORS CREDITORS"),
    ROLE_PAYMENT_REPORT("PAYMENT REPORT"),
    ROLE_RECEIPT_REPORT("RECEIPT REPORT"),

    ROLE_FUEL_TANK("ROLE FUEL TANK"),
    ROLE_RATE_APPROVE("ROLE_RATE_APPROVE"),
    ROLE_SORT("ROLE SORT"),
    ROLE_SORT_APPROVE("ROLE SORT APPROVE"),
    ROLE_PURCHASE_BANK("ROLE PURCHASE BANK"),
    ROLE_SALE_BANK("ROLE SALE BANK"),
    ROLE_SALE_COUPON("ROLE SALE COUPON"),

    ROLE_PURCHASE_SAVE("PURCHASE ENTRY"),
    ROLE_PURCHASE_VERIFY("PURCHASE VERIFY"),
    ROLE_PURCHASE_AUTHORIZE("PURCHASE AUTHORIZE"),
    ROLE_PURCHASE_APPROVE("PURCHASE APPROVE"),

    ROLE_SALES_SAVE("SALES ENTRY"),
    ROLE_SALES_VERIFY("SALES VERIFY"),
    ROLE_SALES_AUTHORIZE("SALES AUTHORIZE"),
    ROLE_SALES_APPROVE("SALES APPROVE")

    final String value

    AuthorityType(String value) {
        this.value = value
    }

    String toString() { value }

    String getKey() { name() }

}